# ============================================================
# BIRE OS — Advanced Trajectory Intelligence (ATI)
# File: src/bire/ati/features.py
# Chapter: 64.0
#
# Created: 2026-06-19
# Updated: 2026-06-19
#
# CHANGED:
# - Added ATI contributor review utilities
# - Added trajectory evidence discovery support
# - Added ATI candidate signal review functions
#
# Purpose:
# ATI feature discovery and trajectory evidence review utilities.
# ATI consumes trajectory-aware evidence generated by other
# domains and supports trajectory interpretation workflows.
# This file contains ATI contributor review, trajectory
# evidence discovery, and future ATI feature utilities.
# ============================================================

import pandas as pd
import numpy as np

def review_ati_contributors(df):
    """
    Review candidate ATI contributors.

    ATI consumes trajectory-aware evidence
    generated by other domains.
    """

    candidate_columns = [
        # Burden
        "vital_burden_score",
        "vital_burden_score_velocity",
        "vital_burden_score_acceleration",

        # Compensation
        "compensation_reserve_score",
        "compensation_reserve_score_velocity",
        "compensation_reserve_score_acceleration",

        # Instability
        "hidden_instability_score",
        "hidden_instability_score_velocity",
        "hidden_instability_score_acceleration",
        "hidden_instability_persistence",

        # Recovery
        "recovery_instability_score",
        "recovery_momentum",

        # Re-Escalation
        "re_escalation_pressure_score",
    ]

    review_rows = []

    for col in candidate_columns:

        review_rows.append({
            "candidate_signal": col,
            "available": col in df.columns,
        })

    return pd.DataFrame(review_rows)

# This function builds a review of the ATI trajectory domains.
def build_ati_domain_review():
    """
    Build ATI trajectory domain review.

    ATI consumes trajectory-oriented evidence
    from multiple domains.
    """

    return pd.DataFrame({
        "trajectory_domain": [
            "Burden",
            "Compensation",
            "Instability",
            "Recovery",
            "Re-Escalation",
        ],

        "candidate_signals": [
            [
                "vital_burden_score",
                "vital_burden_score_velocity",
                "vital_burden_score_acceleration",
            ],

            [
                "compensation_reserve_score",
                "compensation_reserve_score_velocity",
                "compensation_reserve_score_acceleration",
            ],

            [
                "hidden_instability_score",
                "hidden_instability_score_velocity",
                "hidden_instability_score_acceleration",
                "hidden_instability_persistence",
            ],

            [
                "recovery_instability_score",
                "recovery_momentum",
            ],

            [
                "re_escalation_pressure_score",
            ],
        ],

        "status": [
            "Available",
            "Available",
            "Available",
            "Available",
            "Available",
        ],
    })

# This function builds a review of the ATI domain activity.
def build_ati_domain_activity_review():
    """
    ATI domain activity review.

    Activity ratings are based on observations
    gathered during prior HVI and ATI reviews.
    """

    return pd.DataFrame({
        "trajectory_domain": [
            "Burden",
            "Compensation",
            "Instability",
            "Recovery",
            "Re-Escalation",
        ],

        "observed_activity": [
            "Moderate",
            "Moderate",
            "High",
            "Moderate",
            "High",
        ],

        "notable_observation": [
            "Burden signals demonstrated velocity and acceleration activity.",
            "Compensation signals demonstrated velocity and acceleration activity.",
            "Instability signals demonstrated consistent activity, persistence, and acceleration.",
            "Recovery signals demonstrated mixed activity across reviewed families.",
            "Re-escalation pressure demonstrated consistent activity.",
        ],

        "status": [
            "Observation",
            "Observation",
            "Observation",
            "Observation",
            "Observation",
        ],
    })


def build_progressive_burden_prototype():
    """
    ATI interpretation prototype.

    Progressive burden observation.
    """

    return pd.DataFrame({
        "trajectory_domains": [
            "Burden",
            "Instability",
            "Re-Escalation",
        ],

        "observation": [
            "Increasing burden",
            "Increasing instability",
            "Increasing pressure",
        ],

        "ati_interpretation": [
            "Trajectory appears consistent with progressive burden accumulation.",
            "Trajectory appears consistent with progressive burden accumulation.",
            "Trajectory appears consistent with progressive burden accumulation.",
        ],
    })


# This function adds ATI trajectory interpretations to the input DataFrame.
def add_ati_trajectory_interpretations(df):
    """
    ATI interpretation layer.

    Consumes existing trajectory-capable signals.
    Produces patient trajectory interpretation states.

    ATI does not create new HVI measurements.
    ATI does not forecast outcomes.
    """

    out = df.copy()

    required_cols = [
        "hidden_instability_score",
        "hidden_instability_score_velocity",
        "hidden_instability_score_acceleration",
        "hidden_instability_persistence",
        "vital_burden_score",
        "vital_burden_score_velocity",
        "compensation_reserve_score",
        "compensation_reserve_score_velocity",
        "recovery_instability_score",
        "recovery_momentum",
        "re_escalation_pressure_score",
        "false_vital_recovery_signal",
        "recovery_trust_state",
    ]

    missing_cols = [c for c in required_cols if c not in out.columns]

    out["ati_trajectory_state"] = "INSUFFICIENT_TRAJECTORY_CONTEXT"
    out["ati_recovery_state"] = "INSUFFICIENT_TRAJECTORY_CONTEXT"
    out["ati_instability_pattern"] = "INSUFFICIENT_TRAJECTORY_CONTEXT"
    out["ati_rebound_vulnerability"] = "INSUFFICIENT_TRAJECTORY_CONTEXT"
    out["ati_trajectory_summary"] = "Insufficient trajectory context available."

    if missing_cols:
        out["ati_missing_inputs"] = ", ".join(missing_cols)
        return out

    out["ati_missing_inputs"] = ""

    burden_high = out["vital_burden_score"] >= 0.60
    burden_rising = out["vital_burden_score_velocity"] > 0

    compensation_declining = out["compensation_reserve_score_velocity"] < 0
    compensation_present = out["compensation_reserve_score"] > 0

    instability_high = out["hidden_instability_score"] >= 0.60
    instability_rising = out["hidden_instability_score_velocity"] > 0
    instability_accelerating = out["hidden_instability_score_acceleration"] > 0
    instability_persistent = out["hidden_instability_persistence"] >= 2

    recovery_momentum_present = out["recovery_momentum"] > 0
    recovery_instability_high = out["recovery_instability_score"] >= 0.40

    re_escalation_pressure_high = out["re_escalation_pressure_score"] >= 0.40
    false_recovery_present = out["false_vital_recovery_signal"] == 1

    recovery_fragmented = (
        out["recovery_trust_state"]
        .astype(str)
        .str.contains("fragmented", case=False, na=False)
    )

    # --------------------------------------------------------
    # ATI trajectory state
    # --------------------------------------------------------
    out.loc[
        burden_high & burden_rising & instability_high & instability_rising,
        "ati_trajectory_state"
    ] = "PROGRESSIVE_WORSENING"

    out.loc[
        compensation_present & burden_high & ~instability_rising,
        "ati_trajectory_state"
    ] = "FRAGILE_STABILIZATION"

    out.loc[
        recovery_momentum_present & recovery_instability_high,
        "ati_trajectory_state"
    ] = "TEMPORARY_NORMALIZATION"

    out.loc[
        false_recovery_present | recovery_fragmented,
        "ati_trajectory_state"
    ] = "DECEPTIVE_RECOVERY"

    out.loc[
        instability_persistent & instability_high,
        "ati_trajectory_state"
    ] = "PERSISTENT_INSTABILITY_BURDEN"

    out.loc[
        re_escalation_pressure_high & recovery_instability_high,
        "ati_trajectory_state"
    ] = "REBOUND_VULNERABILITY"

    # --------------------------------------------------------
    # ATI recovery state
    # --------------------------------------------------------
    out.loc[
        recovery_momentum_present & ~recovery_instability_high & ~re_escalation_pressure_high,
        "ati_recovery_state"
    ] = "RESILIENT_RECOVERY"

    out.loc[
        recovery_momentum_present & recovery_instability_high,
        "ati_recovery_state"
    ] = "FRAGILE_STABILIZATION"

    out.loc[
        false_recovery_present | recovery_fragmented,
        "ati_recovery_state"
    ] = "DECEPTIVE_RECOVERY"

    out.loc[
        re_escalation_pressure_high & recovery_instability_high,
        "ati_recovery_state"
    ] = "REBOUND_VULNERABILITY"

    # --------------------------------------------------------
    # ATI instability pattern
    # --------------------------------------------------------
    out.loc[
        instability_high & instability_persistent,
        "ati_instability_pattern"
    ] = "PERSISTENT_INSTABILITY_BURDEN"

    out.loc[
        instability_high & instability_rising & instability_accelerating,
        "ati_instability_pattern"
    ] = "PROGRESSIVE_WORSENING"

    out.loc[
        burden_high & compensation_declining & instability_rising,
        "ati_instability_pattern"
    ] = "COMPENSATION_WEAKENING"

    # --------------------------------------------------------
    # ATI rebound vulnerability
    # --------------------------------------------------------
    out.loc[
        re_escalation_pressure_high & recovery_instability_high,
        "ati_rebound_vulnerability"
    ] = "REBOUND_VULNERABILITY"

    out.loc[
        re_escalation_pressure_high & false_recovery_present,
        "ati_rebound_vulnerability"
    ] = "DECEPTIVE_RECOVERY_WITH_REBOUND_PRESSURE"

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------
    out["ati_trajectory_summary"] = np.select(
        [
            out["ati_trajectory_state"].eq("PROGRESSIVE_WORSENING"),
            out["ati_trajectory_state"].eq("PERSISTENT_INSTABILITY_BURDEN"),
            out["ati_trajectory_state"].eq("REBOUND_VULNERABILITY"),
            out["ati_trajectory_state"].eq("DECEPTIVE_RECOVERY"),
            out["ati_trajectory_state"].eq("FRAGILE_STABILIZATION"),
            out["ati_trajectory_state"].eq("TEMPORARY_NORMALIZATION"),
        ],
        [
            "Trajectory appears consistent with progressive worsening.",
            "Trajectory appears consistent with persistent instability burden.",
            "Trajectory appears vulnerable to rebound or re-escalation.",
            "Trajectory appears to contain recovery signals with contradictory or fragmented context.",
            "Trajectory appears temporarily stabilized but may remain fragile.",
            "Trajectory appears improved but does not yet demonstrate durable stability.",
        ],
        default="Insufficient trajectory context available."
    )

    return out

# This function adds a trust layer to the ATI interpretation.
def add_ati_interpretation_trust(df):
    """
    ATI interpretation trust layer.

    Evaluates trustworthiness of ATI
    interpretations using existing
    Playground evidence.
    """

    out = df.copy()

    out["ati_interpretation_trust_state"] = (
        "MODERATE_TRAJECTORY_TRUST"
    )

    fragmented_context = (
        out["recovery_trust_state"]
        .astype(str)
        .str.contains(
            "fragmented",
            case=False,
            na=False,
        )
    )

    false_recovery = (
        out["false_vital_recovery_signal"] == 1
    )

    insufficient_context = (
        out["ati_trajectory_state"]
        ==
        "INSUFFICIENT_TRAJECTORY_CONTEXT"
    )

    out.loc[
        fragmented_context
        | false_recovery,
        "ati_interpretation_trust_state"
    ] = "LOW_TRAJECTORY_TRUST"

    out.loc[
        insufficient_context,
        "ati_interpretation_trust_state"
    ] = "INSUFFICIENT_TRAJECTORY_CONTEXT"

    out.loc[
        (
            out["ati_recovery_state"]
            ==
            "RESILIENT_RECOVERY"
        )
        &
        (~fragmented_context)
        &
        (~false_recovery),
        "ati_interpretation_trust_state"
    ] = "HIGH_TRAJECTORY_TRUST"

    return out

# THis function adds a trajectory behavior layer to the ATI interpretation.
def add_ati_trajectory_behavior(df):
    """
    ATI trajectory behavior layer.

    Consumes existing trajectory-capable signals.
    Produces ATI trajectory behavior outputs.

    Does not create new HVI measurements.
    Does not forecast outcomes.
    """

    out = df.copy()

    required_cols = [
        "hidden_instability_score_velocity",
        "hidden_instability_score_acceleration",
        "vital_burden_score_velocity",
        "compensation_reserve_score_velocity",
        "recovery_momentum",
    ]

    missing_cols = [c for c in required_cols if c not in out.columns]

    out["ati_trajectory_behavior"] = "INSUFFICIENT_TRAJECTORY_CONTEXT"

    if missing_cols:
        out["ati_trajectory_behavior_missing_inputs"] = ", ".join(missing_cols)
        return out

    out["ati_trajectory_behavior_missing_inputs"] = ""

    instability_velocity = out["hidden_instability_score_velocity"]
    instability_acceleration = out["hidden_instability_score_acceleration"]
    burden_velocity = out["vital_burden_score_velocity"]
    compensation_velocity = out["compensation_reserve_score_velocity"]
    recovery_momentum = out["recovery_momentum"]

    has_context = (
        instability_velocity.notna()
        & instability_acceleration.notna()
        & burden_velocity.notna()
        & compensation_velocity.notna()
    )

    improving_aligned = (
        has_context
        & (instability_velocity < 0)
        & (burden_velocity <= 0)
        & (compensation_velocity > 0)
    )

    worsening_aligned = (
        has_context
        & (instability_velocity > 0)
        & (burden_velocity >= 0)
        & (compensation_velocity < 0)
    )

    recovery_supported = (
        improving_aligned
        & (recovery_momentum > 0)
    )

    volatile = (
        has_context
        & (instability_acceleration.abs() > 0.20)
    )

    oscillating = (
        has_context
        & (
            (instability_velocity * burden_velocity < 0)
            | (instability_velocity * compensation_velocity < 0)
        )
        & ~improving_aligned
        & ~worsening_aligned
    )

    stable = (
        has_context
        & (instability_velocity.abs() < 0.01)
        & (burden_velocity.abs() < 1)
        & (compensation_velocity.abs() < 0.01)
    )

    out.loc[
        stable,
        "ati_trajectory_behavior"
    ] = "STABLE_TRAJECTORY"

    out.loc[
        improving_aligned,
        "ati_trajectory_behavior"
    ] = "IMPROVING_TRAJECTORY"

    out.loc[
        recovery_supported,
        "ati_trajectory_behavior"
    ] = "RECOVERY_ALIGNED_TRAJECTORY"

    out.loc[
        worsening_aligned,
        "ati_trajectory_behavior"
    ] = "WORSENING_TRAJECTORY"

    out.loc[
        oscillating,
        "ati_trajectory_behavior"
    ] = "OSCILLATING_TRAJECTORY"

    out.loc[
        volatile,
        "ati_trajectory_behavior"
    ] = "VOLATILE_TRAJECTORY"

    return out

# This function adds an integrated interpretation layer to the ATI data.
def add_ati_integrated_interpretation(df):
    """
    ATI integrated interpretation layer.

    Consumes existing ATI interpretation outputs.
    Produces a synthesized trajectory interpretation.

    Does not create new HVI measurements.
    Does not forecast outcomes.
    Does not create new ATI domains.
    """

    out = df.copy()

    required_cols = [
        "ati_trajectory_state",
        "ati_recovery_state",
        "ati_instability_pattern",
        "ati_rebound_vulnerability",
        "ati_trajectory_behavior",
        "ati_interpretation_trust_state",
    ]

    missing_cols = [c for c in required_cols if c not in out.columns]

    out["ati_integrated_interpretation"] = (
        "Insufficient ATI context available for integrated interpretation."
    )

    if missing_cols:
        out["ati_integrated_missing_inputs"] = ", ".join(missing_cols)
        return out

    out["ati_integrated_missing_inputs"] = ""

    rebound = out["ati_trajectory_state"].eq("REBOUND_VULNERABILITY")
    deceptive = out["ati_trajectory_state"].eq("DECEPTIVE_RECOVERY")

    compensation_weakening = (
        out["ati_instability_pattern"].eq("COMPENSATION_WEAKENING")
    )

    progressive = (
        out["ati_instability_pattern"].eq("PROGRESSIVE_WORSENING")
    )

    worsening = out["ati_trajectory_behavior"].eq("WORSENING_TRAJECTORY")
    volatile = out["ati_trajectory_behavior"].eq("VOLATILE_TRAJECTORY")
    recovery_aligned = out["ati_trajectory_behavior"].eq(
        "RECOVERY_ALIGNED_TRAJECTORY"
    )

    low_trust = out["ati_interpretation_trust_state"].eq(
        "LOW_TRAJECTORY_TRUST"
    )

    out.loc[
        rebound & compensation_weakening & worsening,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with weakening compensation "
        "and worsening behavior."
    )

    out.loc[
        rebound & compensation_weakening & volatile,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with weakening compensation "
        "and volatile behavior."
    )

    out.loc[
        rebound & progressive,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with progressive instability."
    )

    out.loc[
        deceptive & recovery_aligned,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory shows recovery-aligned movement, but recovery context "
        "remains deceptive or fragmented."
    )

    out.loc[
        deceptive & volatile,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory contains deceptive or fragmented recovery context with "
        "volatile behavior."
    )

    out.loc[
        deceptive & low_trust,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory interpretation is limited by deceptive or fragmented "
        "recovery context and low trust."
    )

    rebound = out["ati_trajectory_state"].eq("REBOUND_VULNERABILITY")

    insufficient_instability_context = out[
        "ati_instability_pattern"
    ].eq("INSUFFICIENT_TRAJECTORY_CONTEXT")

    volatile = out[
        "ati_trajectory_behavior"
    ].eq("VOLATILE_TRAJECTORY")

    oscillating = out[
        "ati_trajectory_behavior"
    ].eq("OSCILLATING_TRAJECTORY")

    insufficient_behavior_context = out[
        "ati_trajectory_behavior"
    ].eq("INSUFFICIENT_TRAJECTORY_CONTEXT")

    low_trust = out[
        "ati_interpretation_trust_state"
    ].eq("LOW_TRAJECTORY_TRUST")

    out.loc[
        rebound
        & insufficient_instability_context
        & volatile
        & low_trust,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with volatile behavior, "
        "but instability-pattern context remains insufficient."
    )

    out.loc[
        rebound
        & insufficient_instability_context
        & oscillating
        & low_trust,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with oscillating behavior, "
        "but instability-pattern context remains insufficient."
    )

    out.loc[
        rebound
        & insufficient_instability_context
        & insufficient_behavior_context
        & low_trust,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable, but behavior and "
        "instability-pattern context remain insufficient."
    )

    out.loc[
        rebound
        & compensation_weakening
        & insufficient_behavior_context
        & low_trust,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with weakening compensation, "
        "but trajectory behavior context remains insufficient."
    )

    out.loc[
        rebound
        & compensation_weakening
        & oscillating
        & low_trust,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with weakening compensation "
        "and oscillating behavior."
    )

    out.loc[
        rebound
        & compensation_weakening
        & out["ati_rebound_vulnerability"].eq(
            "DECEPTIVE_RECOVERY_WITH_REBOUND_PRESSURE"
        )
        & oscillating
        & low_trust,
        "ati_integrated_interpretation"
    ] = (
        "Trajectory appears rebound-vulnerable with weakening compensation, "
        "oscillating behavior, and deceptive recovery pressure."
    )
    row_64_24_fix = (
        out["ati_trajectory_state"].eq("REBOUND_VULNERABILITY")
        & out["ati_recovery_state"].eq("REBOUND_VULNERABILITY")
        & out["ati_instability_pattern"].eq("INSUFFICIENT_TRAJECTORY_CONTEXT")
        & out["ati_rebound_vulnerability"].eq("DECEPTIVE_RECOVERY_WITH_REBOUND_PRESSURE")
        & out["ati_trajectory_behavior"].eq("RECOVERY_ALIGNED_TRAJECTORY")
        & out["ati_interpretation_trust_state"].eq("LOW_TRAJECTORY_TRUST")

    )
    out.loc[
        row_64_24_fix,
        "ati_integrated_interpretation"

    ] = (
        "Trajectory shows recovery-aligned movement, but rebound vulnerability "
        "and deceptive recovery pressure remain present with low interpretation trust."
)

    return out



def enforce_ati_earned_trust(df):
    """
    Enforce ATI earned-trust rules.

    High trajectory trust cannot be assigned when
    ATI has not produced a usable integrated interpretation.
    """

    out = df.copy()

    required_cols = [
        "ati_interpretation_trust_state",
        "ati_integrated_interpretation",
    ]

    missing_cols = [
        col for col in required_cols
        if col not in out.columns
    ]

    if missing_cols:
        out["ati_earned_trust_enforcement_missing_inputs"] = (
            ", ".join(missing_cols)
        )
        return out

    out["ati_earned_trust_enforcement_missing_inputs"] = ""

    insufficient_integrated_interpretation = (
        out["ati_integrated_interpretation"]
        .eq("Insufficient ATI context available for integrated interpretation.")
    )

    unearned_high_trust = (
        out["ati_interpretation_trust_state"]
        .eq("HIGH_TRAJECTORY_TRUST")
        & insufficient_integrated_interpretation
    )

    out.loc[
        unearned_high_trust,
        "ati_interpretation_trust_state"
    ] = "MODERATE_TRAJECTORY_TRUST"

    out.loc[
        unearned_high_trust,
        "ati_earned_trust_adjustment"
    ] = "HIGH_TRUST_DOWNGRADED_NO_INTEGRATED_INTERPRETATION"

    out["ati_earned_trust_adjustment"] = (
        out.get("ati_earned_trust_adjustment", "")
        .fillna("")
    )

    return out

# This function adds a column to the DataFrame indicating the sufficiency of trajectory context.
def add_ati_context_sufficiency(df):
    """
    ATI context sufficiency layer.

    Evaluates apparent trajectory context
    availability using existing ATI outputs.
    """

    out = df.copy()

    out["ati_context_sufficiency"] = (
        "LIMITED_TRAJECTORY_CONTEXT"
    )

    insufficient_context = (
        out["ati_trajectory_state"]
        .eq("INSUFFICIENT_TRAJECTORY_CONTEXT")
    )

    insufficient_instability = (
        out["ati_instability_pattern"]
        .eq("INSUFFICIENT_TRAJECTORY_CONTEXT")
    )

    insufficient_behavior = (
        out["ati_trajectory_behavior"]
        .eq("INSUFFICIENT_TRAJECTORY_CONTEXT")
    )

    low_trust = (
        out["ati_interpretation_trust_state"]
        .eq("LOW_TRAJECTORY_TRUST")
    )

    high_trust = (
        out["ati_interpretation_trust_state"]
        .eq("HIGH_TRAJECTORY_TRUST")
    )

    out.loc[
        insufficient_context
        & insufficient_instability
        & insufficient_behavior,
        "ati_context_sufficiency"
    ] = "INSUFFICIENT_TRAJECTORY_CONTEXT"

    out.loc[
        high_trust
        & (~insufficient_context)
        & (~insufficient_behavior),
        "ati_context_sufficiency"
    ] = "SUFFICIENT_TRAJECTORY_CONTEXT"

    out.loc[
        low_trust
        & insufficient_instability,
        "ati_context_sufficiency"
    ] = "LIMITED_TRAJECTORY_CONTEXT"

    return out

# This function adds a column to the DataFrame indicating the state of fragmented context.
def add_ati_fragmented_context_state(df):
    """
    ATI fragmented context reconstruction.

    Determines whether trajectory meaning
    remains reconstructable despite
    fragmented context.

    ATI does not reconstruct data.

    ATI determines whether enough
    trajectory meaning remains available
    for honest interpretation.
    """

    out = df.copy()

    out["ati_fragmented_context_state"] = (
        "NON_RECONSTRUCTABLE_CONTEXT"
    )

    has_trajectory_state = (
        ~out["ati_trajectory_state"]
        .eq("INSUFFICIENT_TRAJECTORY_CONTEXT")
    )

    has_behavior = (
        ~out["ati_trajectory_behavior"]
        .eq("INSUFFICIENT_TRAJECTORY_CONTEXT")
    )

    has_instability_context = (
        ~out["ati_instability_pattern"]
        .eq("INSUFFICIENT_TRAJECTORY_CONTEXT")
    )

    sufficient_context = (
        out["ati_context_sufficiency"]
        .eq("SUFFICIENT_TRAJECTORY_CONTEXT")
    )

    limited_context = (
        out["ati_context_sufficiency"]
        .eq("LIMITED_TRAJECTORY_CONTEXT")
    )

    reconstructable = (
        (
            has_trajectory_state
            & has_behavior
        )
        |
        (
            has_trajectory_state
            & has_instability_context
        )
        |
        sufficient_context
    )

    out.loc[
        reconstructable,
        "ati_fragmented_context_state"
    ] = "RECONSTRUCTABLE_CONTEXT"

    return out

def rebuild_ati_v1(df):
    """
    Rebuild ATI v1 outputs from the provided source dataframe.
    """

    out = df.copy()

    out = add_ati_trajectory_interpretations(out)
    out = add_ati_trajectory_behavior(out)
    out = add_ati_interpretation_trust(out)
    out = add_ati_integrated_interpretation(out)
    out = add_ati_context_sufficiency(out)
    out = add_ati_fragmented_context_state(out)
    out = enforce_ati_earned_trust(out)

    return out